#Minecraft server properties
#Tue May 12 17:49:24 UTC 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=easy
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=HnUIQzSozdAS9E00KA6tE2nTRbKhBeBdAw6SXVt0
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=200
max-tick-time=60000
max-world-size=29999984
motd=§x§f§f§6§6§0§0§lM§x§f§f§6§1§0§c§li§x§f§f§5§c§1§8§ln§x§f§f§5§7§2§4§le§x§f§f§5§3§3§1§lC§x§f§f§4§e§3§d§lr§x§f§f§4§9§4§9§la§x§f§f§4§4§5§5§lf§x§f§f§3§f§6§1§lt§x§f§f§3§a§6§d§l §x§f§f§3§5§7§9§lR§x§f§f§3§1§8§6§le§x§f§f§2§c§9§2§lc§x§f§f§2§7§9§e§lo§x§f§f§2§2§a§a§lr§x§f§f§1§d§b§6§ld§x§f§f§1§8§c§2§li§x§f§f§1§3§c§e§ln§x§f§f§0§f§d§b§lg§x§f§f§0§a§e§7§ls§x§f§f§0§5§f§3§l 
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
